version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d

  exchange:
    build: gw-exchanger/
    depends_on:
      - db
    ports:
      - "44044:44044"
      - "8181:8181"
    volumes:
      - ./gw-exchanger/config:/config

  cache:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  currency-wallet:
    build: gw-currency-wallet/
    depends_on:
      - db
      - cache
      - exchange
    ports:
      - "8080:8080"
      - "8282:8282"
    volumes:
      - ./gw-currency-wallet/config:/config

volumes:
  redis-data:
