// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/grpcclient/service.go

// Package mockclient is a generated GoMock package.
package mockclient

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kossadda/wallet-exchanger/currency-wallet/internal/model"
	exchange_grpc "github.com/kossadda/wallet-exchanger/share/gen/exchange"
)

// MockMainAPI is a mock of MainAPI interface.
type MockMainAPI struct {
	ctrl     *gomock.Controller
	recorder *MockMainAPIMockRecorder
}

// MockMainAPIMockRecorder is the mock recorder for MockMainAPI.
type MockMainAPIMockRecorder struct {
	mock *MockMainAPI
}

// NewMockMainAPI creates a new mock instance.
func NewMockMainAPI(ctrl *gomock.Controller) *MockMainAPI {
	mock := &MockMainAPI{ctrl: ctrl}
	mock.recorder = &MockMainAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMainAPI) EXPECT() *MockMainAPIMockRecorder {
	return m.recorder
}

// CloseGRPC mocks base method.
func (m *MockMainAPI) CloseGRPC() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseGRPC")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseGRPC indicates an expected call of CloseGRPC.
func (mr *MockMainAPIMockRecorder) CloseGRPC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseGRPC", reflect.TypeOf((*MockMainAPI)(nil).CloseGRPC))
}

// ExchangeSum mocks base method.
func (m *MockMainAPI) ExchangeSum(ctx context.Context, input *model.Exchange) ([]float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeSum", ctx, input)
	ret0, _ := ret[0].([]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeSum indicates an expected call of ExchangeSum.
func (mr *MockMainAPIMockRecorder) ExchangeSum(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeSum", reflect.TypeOf((*MockMainAPI)(nil).ExchangeSum), ctx, input)
}

// GetExchangeRates mocks base method.
func (m *MockMainAPI) GetExchangeRates(ctx context.Context) (*exchange_grpc.ExchangeRatesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRates", ctx)
	ret0, _ := ret[0].(*exchange_grpc.ExchangeRatesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRates indicates an expected call of GetExchangeRates.
func (mr *MockMainAPIMockRecorder) GetExchangeRates(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRates", reflect.TypeOf((*MockMainAPI)(nil).GetExchangeRates), ctx)
}
